### ISSUE TITLE
Admin Contract

### ISSUE THREAD

**Issue by kubaplas** [make-software/dao-contracts#29]
# Admin
This contract allows voting for changes in whitelists and change of the owner of the contracts that Admin Contract owns, that is:
- VariableRepo
- KYC
- ReputationToken

The voting mechanism is the same as used in RepoVoter Contract #28 with the only difference being different actions are being executed.

### votings
Stores votings, their configuration and their votes.
```rust
votings: TBD
```
### other
```rust
variable_repo: Address,
reputation_token: Address,
kyc_contract: Address,
Contracts: Enum(variable_repo, reputation_token, kyc_contract),
Actions: Enum(add_to_whitelist, remove_from_whitelist, change_owner)
```

### init
Initializes the contract with addresses of ReputationToken, VariableRepo and KYC contracts
```rust
fn init(&mut self, variable_repo: Address, reputation_token: Address, kyc_contract: Address);
```

### create_voting
Creates a new voting. We pass as arguments which contract we want act on, an action and an address which will be a parameter for the action.
```rust
fn create_voting(
&mut self,
subject: Contracts,
action: Actions,
argument: Address,
stake: U256
)
```
Successful call emits an Event:
```rust
AdminVotingCreated(
  subject: Contracts,
  action: Actions,
  argument: Address,
  stake: U256,
  creator: Address,
  informal_voting_id: U256,
  informal_voting_finish_time: U256,
  informal_voting_quorum: U32,
  formal_voting_id: U256,
  formal_voting_finish_time: U256,
  formal_voting_quorum: U32
)
```

### vote
Is the same as in RepoVoter Contract #28

### finish_voting
Is the same as in RepoVoter Contract #28, with different actions being called in a subject contract.

**Comment by zie1ony** [comment]
Done
