### ISSUE TITLE
KYC Contract Skeleton

### ISSUE THREAD

**Issue by kubaplas** [make-software/dao-contracts#30]
# KYC Contract skeleton
To fully implement contracts that use voting, we need a KYC Contract. But before its specification is cooked, we can use this skeleton with basic implementation for testing other contracts.

### has_kyc
This method will return if the user owning a given address is eligible - has passed the KYC process.
```rust
fn has_kyc(&self, address: Address)
```
In the Skeleton, this method will always return true.

**Comment by zie1ony** [comment]
Done.
